DELIMITER $$
CREATE PROCEDURE PPN_S_DEPARTAMENTO (
    OUT R_CODIGO INTEGER, 
    OUT R_MENSAJE VARCHAR(100)
) 
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION 
	BEGIN
		GET DIAGNOSTICS CONDITION 1 R_CODIGO = RETURNED_SQLSTATE, R_MENSAJE = MESSAGE_TEXT;
		ROLLBACK;
	END;
START TRANSACTION;
	SET R_CODIGO = 1;
	SET R_MENSAJE = 'CONSULTA EXITOSA';
	
    SELECT D.ID, D.NOMBRE, D.UBIGEO, D.UBIGEO_RENIEC FROM DEPARTAMENTO D;
END$$

CREATE PROCEDURE PPN_S_PROVINCIA (
    IN I_ID_DEPARTAMENTO INT, 
    OUT R_CODIGO INTEGER, 
    OUT R_MENSAJE VARCHAR(100)
) 
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION 
	BEGIN
		GET DIAGNOSTICS CONDITION 1 R_CODIGO = RETURNED_SQLSTATE, R_MENSAJE = MESSAGE_TEXT;
		ROLLBACK;
	END;
START TRANSACTION;
	SET R_CODIGO = 1;
	SET R_MENSAJE = 'CONSULTA EXITOSA';
	SELECT D.ID, D.ID_DEPARTAMENTO, D.NOMBRE, D.UBIGEO, D.UBIGEO_RENIEC FROM PROVINCIA D WHERE D.ID_DEPARTAMENTO = I_ID_DEPARTAMENTO;
END$$

CREATE PROCEDURE PPN_S_DISTRITO (
    IN I_ID_PROVINCIA INT, 
    OUT R_CODIGO INTEGER, 
    OUT R_MENSAJE VARCHAR(100)
) 
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION 
	BEGIN
		GET DIAGNOSTICS CONDITION 1 R_CODIGO = RETURNED_SQLSTATE, R_MENSAJE = MESSAGE_TEXT;
		ROLLBACK;
	END;
START TRANSACTION;
	SET R_CODIGO = 1;
	SET R_MENSAJE = 'CONSULTA EXITOSA';
	SELECT D.ID, D.ID_PROVINCIA, D.NOMBRE, D.UBIGEO, D.UBIGEO_RENIEC FROM DISTRITO D WHERE D.ID_PROVINCIA = I_ID_PROVINCIA;
END$$

CREATE PROCEDURE PPN_I_POSTULANTE (
    IN I_DNI VARCHAR(11), 
	IN I_NOMBRE VARCHAR(50),
	IN I_APELLIDO_PAT VARCHAR(50),
	IN I_APELLIDO_MAT VARCHAR(50),
	IN I_CELULAR VARCHAR(15),
	IN I_EMAIL VARCHAR(50),
	IN I_DIRECCION VARCHAR(50),
	IN I_ID_DEPARTAMENTO INT, 
	IN I_ID_PROVINCIA INT, 
	IN I_ID_DISTRITO INT, 
    OUT R_CODIGO INTEGER, 
    OUT R_MENSAJE VARCHAR(100)
) 
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION 
	BEGIN
		GET DIAGNOSTICS CONDITION 1 R_CODIGO = RETURNED_SQLSTATE, R_MENSAJE = MESSAGE_TEXT;
		ROLLBACK;
	END;
START TRANSACTION;
	SET R_CODIGO = 1;
	SET R_MENSAJE = 'CONSULTA EXITOSA';
	INSERT INTO POSTULANTE(DNI,NOMBRE,APELLIDO_PAT,APELLIDO_MAT,CELULAR,EMAIL,DIRECCION,ID_DEPARTAMENTO,ID_PROVINCIA,ID_DISTRITO,FECHA_INSCRIPCION)
	VALUES (I_DNI,I_NOMBRE,I_APELLIDO_PAT,I_APELLIDO_MAT,I_CELULAR,I_EMAIL,I_DIRECCION,I_ID_DEPARTAMENTO,I_ID_PROVINCIA,I_ID_DISTRITO,NOW());
	COMMIT;

	SELECT MAX(P.ID) AS ID FROM POSTULANTE P;
END$$

DELIMITER ;